# Random Sampling with NumPy

In [2]:
import numpy as np
import random 

In [3]:
np.random.random(1)

array([0.48129061])

In [4]:
np.random.random((3,3))

array([[0.19824193, 0.49900178, 0.44009123],
       [0.16783162, 0.2448456 , 0.27116162],
       [0.40830931, 0.12562585, 0.39088734]])

In [5]:
np.random.randint(1,4)

3

In [6]:
np.random.randint(1,4, (4,4))

array([[3, 2, 3, 2],
       [2, 3, 2, 2],
       [3, 1, 3, 1],
       [3, 2, 1, 1]], dtype=int32)

In [7]:
np.random.randint(1,4, (2,4,4))

array([[[2, 2, 2, 3],
        [2, 2, 3, 2],
        [3, 2, 2, 1],
        [3, 2, 3, 1]],

       [[3, 2, 1, 3],
        [2, 2, 2, 2],
        [1, 3, 3, 3],
        [1, 3, 3, 2]]], dtype=int32)

In [8]:
np.random.seed(10)
np.random.randint(1,4, (2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]], dtype=int32)

In [9]:
np.random.seed(10)
np.random.randint(1,4, (2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]], dtype=int32)

In [10]:
np.random.rand(3)

array([0.13145815, 0.41366737, 0.77872881])

In [11]:
np.random.rand(3,3)

array([[0.58390137, 0.18263144, 0.82608225],
       [0.10540183, 0.28357668, 0.06556327],
       [0.05644419, 0.76545582, 0.01178803]])

In [12]:
np.random.randn(3,3)

array([[-1.58494101,  1.05535316, -1.92657911],
       [ 0.69858388, -0.74620143, -0.15662666],
       [-0.19363594,  1.13912535,  0.36221796]])

In [13]:
x = [1,2,3,4]
np.random.choice(x)

np.int64(1)

In [14]:
np.random.choice(x)

np.int64(1)

In [15]:
np.random.choice(x)

np.int64(1)

In [16]:
for i in range(20):
    print(np.random.choice(x))

2
1
4
1
1
3
1
3
3
1
4
2
1
4
2
3
3
2
3
3


In [17]:
x

[1, 2, 3, 4]

In [18]:
np.random.permutation(x)

array([2, 3, 1, 4])

In [19]:
np.random.permutation(x)

array([2, 3, 4, 1])