# NumPy Functions :

In [3]:
import numpy as np

# arange()

In [13]:
#np.arange(start, end , steps)
ar1_1d = np.arange(1,13) 
print(ar_1d)

[ 1  3  5  7  9 11]


In [14]:
ar2_1d = np.arange(1,13,2) 
print(ar_1d)

[ 1  3  5  7  9 11]


# linspace() 

In [7]:
np.linspace(1,5,4) 

array([1.        , 2.33333333, 3.66666667, 5.        ])

# reshape()

In [15]:
ar_2d = ar1_1d.reshape(3,4)
print(ar_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
ar_23d = ar1_1d.reshape(2,3,2)
print(ar_23d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [17]:
ar = np.arange(1,13).reshape(2,6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# ravel()

In [18]:
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten()

In [19]:
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# transpose()

In [20]:
ar.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [21]:
ar.T

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])